# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

# Packages needed to generate model predictions
if (FALSE) {
    library(dials)
    library(dplyr)
    library(parsnip)
    library(purrr)
    library(ranger)
    library(recipes)
    library(rlang)
    library(rsample)
    library(tibble)
    library(tidyr)
    library(tune)
    library(vctrs)
    library(workflows)
    library(yardstick)
}
b <- board_folder(path = "/var/folders/1q/4dfpcn592cjdlnzwjnx6dx400000gn/T/RtmpGec5gh/pins-a1873c4ad4e1")
v <- vetiver_pin_read(b, "rf_bees", version = "20220113T043810Z-43c68")

#* @plumber
function(pr) {
    pr %>% vetiver_pr_predict(v)
}
